env:
  browser: true
  commonjs: true
  cypress/globals: true
  es6: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
plugins: [
    "cypress"
  ]
rules: {
  "indent": ["error", 4],
  { "tabWidth": 4 }
}
